-- Insert sample record 
EXEC sp_CreatePWDRecord
    @regNumber = '973821289540',
    @regDate = '2025-10-13',
    @lastName = 'Karamazov',
    @firstName = 'Ivan',
    @middleName = 'Fyodor',
    @disability = 'Learning Disability',
    @street = 'b1 b2',
    @barangay = 'sabang',
    @municipality = 'dasma',
    @province = 'cavite',
    @region = 'iv a',
    @tel = '1234567',
    @mobile = '9123456789',
    @email = 'ivan@email.com',
    @dob = '2025-09-04',
    @sex = 'Male',
    @nationality = 'Filipino',
    @blood = 'A+',
    @civil = 'Single',
    @emergencyName = 'Keanu Oneal',
    @emergencyPhone = '9123456789',
    @emergencyRelationship = 'Test',
    @proofIdentity = 'sample-id.png',
    @proofDisability = 'sample-medcert.png',
    @password = '83185255',
    @status = 'denied';
GO

-- More sample data
EXEC sp_CreatePWDRecord
    @regNumber = '973821289541',
    @regDate = '2025-10-14',
    @lastName = 'Dela Cruz',
    @firstName = 'Juan',
    @middleName = 'Santos',
    @disability = 'Visual Impairment',
    @street = '123 Main Street',
    @barangay = 'Poblacion',
    @municipality = 'Imus',
    @province = 'Cavite',
    @region = 'iv a',
    @tel = '2345678',
    @mobile = '9123456790',
    @email = 'juan.delacruz@email.com',
    @dob = '1990-05-15',
    @sex = 'Male',
    @nationality = 'Filipino',
    @blood = 'O+',
    @civil = 'Married',
    @emergencyName = 'Maria Dela Cruz',
    @emergencyPhone = '9123456791',
    @emergencyRelationship = 'Spouse',
    @proofIdentity = 'juan-id.png',
    @proofDisability = 'juan-medcert.png',
    @password = 'password123',
    @status = 'approved';
GO